"""audit_events

Revision ID: 9ab613851105
Revises: 
Create Date: 2026-05-05 10:47:52.010140

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('study_instance_uid', sa.String(length=128), nullable=True),
    sa.Column('series_instance_uid', sa.String(length=128), nullable=True),
    sa.Column('sop_instance_uid', sa.String(length=128), nullable=True),
    sa.Column('orthanc_instance_id', sa.String(length=128), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_audit_created_at', 'audit_events', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_event_type', 'audit_events', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_event_type', table_name='audit_events')
    op.drop_index('idx_audit_created_at', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
