"""reconstruction_jobs

Revision ID: c4bd4e9c2353
Revises: 001
Create Date: 2026-05-07 08:43:50.198462

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "002"
down_revision: str | None = "001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconstruction_jobs",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("input_file_name", sa.String(length=256), nullable=False),
        sa.Column("input_format", sa.String(length=8), nullable=False),
        sa.Column("input_shape", sa.String(length=64), nullable=True),
        sa.Column("output_dicom_uid", sa.String(length=128), nullable=True),
        sa.Column("output_orthanc_instance_id", sa.String(length=128), nullable=True),
        sa.Column("psnr_db", sa.Double(), nullable=True),
        sa.Column("ssim", sa.Double(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id"),
    )
    op.create_index(
        "idx_recon_created_at",
        "reconstruction_jobs",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_recon_status", "reconstruction_jobs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_recon_status", table_name="reconstruction_jobs")
    op.drop_index("idx_recon_created_at", table_name="reconstruction_jobs")
    op.drop_table("reconstruction_jobs")
    # ### end Alembic commands ###
