"""storage_objects

Revision ID: d93c75f8dcb4
Revises: 002
Create Date: 2026-05-12 09:24:55.857070

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "003"
down_revision: str | None = "002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_objects",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("bucket", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.String(length=256), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bucket", "object_key", name="uq_storage_bucket_key"),
    )
    op.create_index("idx_storage_created_at", "storage_objects", ["created_at"], unique=False)
    op.create_index("idx_storage_sha256", "storage_objects", ["sha256"], unique=False)
    op.create_index("idx_storage_source", "storage_objects", ["source"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_storage_source", table_name="storage_objects")
    op.drop_index("idx_storage_sha256", table_name="storage_objects")
    op.drop_index("idx_storage_created_at", table_name="storage_objects")
    op.drop_table("storage_objects")
    # ### end Alembic commands ###
